import * as fs from "node:fs/promises";
import path from "node:path";

import type { AutoResolveConfig } from "../../types";
import { isNonCompletionContent } from "./lifecycle-store";
import type { LifecycleStore } from "./lifecycle-store";
import { insertPlanRowBefore, updateDependsOnColumn } from "./plan-editor";
import type { PlanRowData } from "./plan-editor";
import { parseDispatchPlanRows } from "../../tool-gateway/tools/dispatch-status";

// ---------------------------------------------------------------------------
// Public interfaces
// ---------------------------------------------------------------------------

export interface AutoResolveDeps {
  log: {
    info(message: string, meta?: Record<string, unknown>): void;
    warn(message: string, meta?: Record<string, unknown>): void;
  };
  writeWorkerFile: (filePath: string, content: string) => Promise<void>;
}

export interface AutoResolveReport {
  generated: Array<{ fixWorkerId: string; blockedWorkerId: string }>;
  retried: string[];
  escalated: string[];
  skipped: string[];
}

// ---------------------------------------------------------------------------
// Default deps
// ---------------------------------------------------------------------------

function defaultDeps(): AutoResolveDeps {
  return {
    log: {
      info: (msg, meta) => console.log(msg, meta),
      warn: (msg, meta) => console.warn(msg, meta)
    },
    writeWorkerFile: (filePath, content) => fs.writeFile(filePath, content, "utf8")
  };
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

export function extractBlockerSummary(content: string): string {
  const lines = content.split(/\r?\n/).filter((line) => {
    const trimmed = line.trim();
    if (trimmed.length === 0) return false;
    if (/^⛔\s*BLOCKED\s*[—–-]?\s*$/i.test(trimmed)) return false;
    if (/^⏸\s*PAUSE\s*[—–-]?\s*$/i.test(trimmed)) return false;
    if (/^BLOCKED\s*[—–-]\s*$/i.test(trimmed)) return false;
    if (/^PAUSE\s*[—–-]\s*$/i.test(trimmed)) return false;
    return true;
  });

  // Strip BLOCKED/PAUSE marker prefix from the first substantive line
  const first = lines[0] ?? "";
  const stripped = first
    .replace(/^⛔\s*BLOCKED\s*[—–-]\s*/i, "")
    .replace(/^⏸\s*PAUSE\s*[—–-]\s*/i, "")
    .replace(/^BLOCKED\s*[—–-]\s*/i, "")
    .replace(/^PAUSE\s*[—–-]\s*/i, "")
    .trim();

  if (stripped.length === 0) return content.slice(0, 80).trim();
  return stripped.length > 80 ? `${stripped.slice(0, 77)}...` : stripped;
}

export function shouldEscalateToHuman(content: string, patterns: RegExp[]): boolean {
  return patterns.some((pattern) => pattern.test(content));
}

function generateFixWorkerFile(
  fixWorkerId: string,
  blockedWorkerId: string,
  blockerContent: string
): string {
  return `### ${fixWorkerId} — Resolve Blocker for ${blockedWorkerId}

- **Runtime**: Local (bash)
- **Delta Type**: REWORK
- **Phase**: 0
- **Priority**: P0
- **Depends on**: —

#### Blocker Context
\`\`\`
${blockerContent}
\`\`\`

#### Sub-tasks
${fixWorkerId}.1 — Diagnose and fix the blocker
${fixWorkerId}.2 — Verify the fix

#### AI Auto-Tests
[placeholder for worker to fill]

#### Completion Protocol
1. Create a feature branch if not already on one
2. Commit all changes with a descriptive message
3. Push the branch and create a PR if applicable
4. Report completion with a summary of what was fixed
`;
}

async function generateFixTask(
  planPath: string,
  blockedWorkerId: string,
  fixWorkerId: string,
  blockerContent: string,
  config: AutoResolveConfig,
  deps: AutoResolveDeps
): Promise<void> {
  // Read the plan to find the blocked worker's batch
  const planMarkdown = await fs.readFile(planPath, "utf8");
  const rows = parseDispatchPlanRows(planMarkdown);
  const blockedRow = rows.find((r) => r.worker_id === blockedWorkerId);
  const batch = blockedRow?.batch ?? "0";

  // Generate and write the worker file
  const workerFileContent = generateFixWorkerFile(fixWorkerId, blockedWorkerId, blockerContent);
  const workerFilePath = path.join(config.taskspecDir, `${fixWorkerId}.md`);
  await deps.writeWorkerFile(workerFilePath, workerFileContent);

  // Build the new plan row
  const summary = extractBlockerSummary(blockerContent);
  const newRow: PlanRowData = {
    status: "⬜",
    batch,
    worker_id: fixWorkerId,
    task: `Resolve blocker: ${summary}`,
    model: "CODEX-HIGH",
    depends_on: "—",
    notes: "Auto-generated by dispatcher"
  };

  // Insert FIX row above the blocked worker in the plan
  let updatedPlan = insertPlanRowBefore(planMarkdown, blockedWorkerId, newRow);

  // Update blocked worker's Depends On to include FIX worker
  updatedPlan = updateDependsOnColumn(updatedPlan, blockedWorkerId, fixWorkerId);

  // Write updated plan
  await fs.writeFile(planPath, updatedPlan, "utf8");
}

// ---------------------------------------------------------------------------
// Main function
// ---------------------------------------------------------------------------

export async function autoResolve(
  lifecycleStore: LifecycleStore,
  planPath: string,
  config: AutoResolveConfig,
  deps?: AutoResolveDeps
): Promise<AutoResolveReport> {
  const resolvedDeps = deps ?? defaultDeps();

  const report: AutoResolveReport = {
    generated: [],
    retried: [],
    escalated: [],
    skipped: []
  };

  if (!config.enabled) {
    return report;
  }

  // Load lifecycle state and plan
  const state = lifecycleStore.load();
  const planMarkdown = await fs.readFile(planPath, "utf8");
  const planRows = parseDispatchPlanRows(planMarkdown);
  const planWorkerIds = new Set(planRows.map((r) => r.worker_id));

  // Check each active or newly-failed worker for BLOCKED/PAUSE content. BLOCKED
  // replies are terminal for status reporting, but still eligible for an
  // auto-generated FIX task.
  for (const [workerId, worker] of Object.entries(state.workers)) {
    if (worker.status !== "running" && worker.status !== "failed") continue;
    if (!worker.hub_result?.content) continue;
    if (!isNonCompletionContent(worker.hub_result.content)) continue;

    const fixWorkerId = `FIX-${workerId}`;
    const blockerContent = worker.hub_result.content;

    if (!planWorkerIds.has(fixWorkerId)) {
      // No FIX row exists yet
      if (shouldEscalateToHuman(blockerContent, config.humanEscalationPatterns)) {
        resolvedDeps.log.warn("Blocker requires human escalation", {
          worker_id: workerId,
          content: blockerContent
        });
        report.escalated.push(workerId);
        continue;
      }

      // Generate a FIX task
      await generateFixTask(planPath, workerId, fixWorkerId, blockerContent, config, resolvedDeps);
      report.generated.push({ fixWorkerId, blockedWorkerId: workerId });

      resolvedDeps.log.info("Generated FIX task", {
        fix_worker_id: fixWorkerId,
        blocked_worker_id: workerId
      });
    } else {
      // FIX row exists — check the FIX worker's lifecycle status
      const fixWorker = state.workers[fixWorkerId];
      const fixStatus = fixWorker?.status;

      if (fixStatus === "completed") {
        // Reset the blocked worker to pending
        lifecycleStore.setWorkerStatus(workerId, "pending", "auto_resolve:fix_completed", {
          clearHubResult: true,
          incrementRetryCount: false,
          resetRetryCount: true
        });
        report.retried.push(workerId);

        resolvedDeps.log.info("Reset blocked worker after FIX completed", {
          worker_id: workerId,
          fix_worker_id: fixWorkerId
        });
      } else if (fixStatus === "failed" || fixStatus === "abandoned") {
        resolvedDeps.log.warn("FIX worker ended in terminal failure state", {
          worker_id: workerId,
          fix_worker_id: fixWorkerId,
          fix_status: fixStatus
        });
        report.escalated.push(workerId);
      } else {
        // pending, running, or no lifecycle entry — skip
        report.skipped.push(workerId);
      }
    }
  }

  return report;
}
