import { describe, expect, it } from "vitest";
import { insertPlanRowBefore, updateDependsOnColumn } from "../plan-editor";

describe("insertPlanRowBefore", () => {
  const basePlan = [
    "| Status | Batch | Worker | Task | Model | Depends On | Notes |",
    "|--------|-------|--------|------|-------|------------|-------|",
    "| ⬜ | 0 | PRE-FLIGHT | Env Health Check | SONNET | — | |",
    "| ⬜ | 1 | R-01 | Implement feature | OPUS | PRE-FLIGHT | |",
    ""
  ].join("\n");

  it("inserts a row immediately above the target worker", () => {
    const newRow = {
      status: "⬜",
      batch: "0",
      worker_id: "FIX-PRE-FLIGHT",
      task: "Resolve blocker: baseline test failure",
      model: "CODEX-HIGH",
      depends_on: "—",
      notes: "Auto-generated by dispatcher"
    };

    const result = insertPlanRowBefore(basePlan, "PRE-FLIGHT", newRow);
    const lines = result.split("\n");
    const fixIndex = lines.findIndex((l) => l.includes("FIX-PRE-FLIGHT"));
    const preFlightIndex = lines.findIndex((l) => l.includes("| PRE-FLIGHT |"));
    expect(fixIndex).toBeGreaterThan(0);
    expect(fixIndex).toBeLessThan(preFlightIndex);
  });

  it("throws if target worker is not found", () => {
    expect(() => insertPlanRowBefore(basePlan, "NONEXISTENT", {
      status: "⬜", batch: "0", worker_id: "FIX-X", task: "fix",
      model: "CODEX-HIGH", depends_on: "—", notes: ""
    })).toThrow("not found");
  });

  it("preserves all existing rows", () => {
    const newRow = {
      status: "⬜", batch: "0", worker_id: "FIX-PRE-FLIGHT",
      task: "Fix", model: "CODEX-HIGH", depends_on: "—", notes: ""
    };
    const result = insertPlanRowBefore(basePlan, "PRE-FLIGHT", newRow);
    expect(result).toContain("| PRE-FLIGHT |");
    expect(result).toContain("| R-01 |");
    expect(result).toContain("| FIX-PRE-FLIGHT |");
  });
});

describe("updateDependsOnColumn", () => {
  const plan = [
    "| Status | Batch | Worker | Task | Model | Depends On | Notes |",
    "|--------|-------|--------|------|-------|------------|-------|",
    "| 🔄 | 0 | PRE-FLIGHT | Env Check | SONNET | — | |",
    ""
  ].join("\n");

  it("adds a dependency to a worker's Depends On column", () => {
    const result = updateDependsOnColumn(plan, "PRE-FLIGHT", "FIX-PRE-FLIGHT");
    expect(result).toContain("FIX-PRE-FLIGHT");
  });

  it("replaces dash placeholder when adding first dependency", () => {
    const result = updateDependsOnColumn(plan, "PRE-FLIGHT", "FIX-PRE-FLIGHT");
    const row = result.split("\n").find((l) => l.includes("PRE-FLIGHT") && !l.includes("FIX-PRE-FLIGHT"));
    expect(row).toBeUndefined();
  });

  it("appends to existing dependencies", () => {
    const planWithDep = plan.replace("— |", "R-01 |");
    const result = updateDependsOnColumn(planWithDep, "PRE-FLIGHT", "FIX-PRE-FLIGHT");
    expect(result).toMatch(/R-01.*FIX-PRE-FLIGHT|FIX-PRE-FLIGHT.*R-01/);
  });
});
